ifdef BCM_KF # defined(CONFIG_BCM_KF_ANDROID)
# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o

endif # BCM_KF # defined(CONFIG_BCM_KF_ANDROID)
