/* this file is automatically generated from top level Makefile */
#ifndef __BCM_SWVERSION_H__
#define __BCM_SWVERSION_H__
#define BCM_REL_VERSION 31
#define BCM_REL_RELEASE 164
#define BCM_REL_PATCH 18
#define BCM_SW_VERSIONCODE (31*65536+164*256+18)
#define BCM_SW_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))
#endif
