obj-$(CONFIG_SFP_LASER) += aei_sfp_laser_dev.o

aei_sfp_laser_dev-objs += aei_sfp_laser_dev_dep.o

$(obj)/aei_sfp_laser_dev_dep.o:
	cp $(obj)/aei_sfp_laser_dev$(PROFILE).o_save $(obj)/aei_sfp_laser_dev_dep.o

applinks:

